spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 105072Li
    hikari:
      pool-name: DateHikariC
      minimum-idle: 5
      idle-timeout: 18000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
jwt:
  tokenHeader: Authorization
  secret: eiorjeowijfioewjfdksjfoisd
  expiration: 1800000
  tokenHead: Bearer
#  mybatis 
mybatis:
  mapper-locations: classpath*:mapper/*.xml